### ISSUE TITLE
language loading problem (default=german, user=english)

### ISSUE THREAD

**Issue by flohmueller** [mantisbt-plugins/source-integration#113]
Hi there.. 
in my configuration I have set **$g_default_language = 'german';**, but in my user account the language is set to **english**.
Now there's a language loading problem when **SourceGeneric\register()** method is called. 
I debugged mantis' **lang_api** and could see that all german language strings were already loaded into **$g_lang_strings['german']**, but in **$g_lang_strings['english']** there were only non-plugin strings.
In the course of **lang_get** mantis tried to load language files from "[...]/plugins/SourceGeneric" folder which clearly doesn't exist.

I could "fix" this issue by calling **plugin_push_current( 'Source' );** at the beginning  and **plugin_pop_current();** and the end of **SourceGenericPlugin\register()** in **MantisSourcePlugin.class.php**. Now **lang_get** looked in the correct subfolder "[...]/plugins/Source" and no error occured.

Can anyone tell if that's a legitimate fix or if it could arise other problems that I'm not aware of atm. !?

Best regards, Florian

**Comment by dregad** [comment]
Hi Florian

> Now there's a language loading problem when SourceGeneric\register() method is called. 

For my understanding, can you explain exactly what the problem is, and describe how I could reproduce it after setting languages as you indicated ?

> I could "fix" this issue by calling plugin_push_current [...]

Thanks for your investigation. I find it quite strange that you would have to push/pop the *Source* plugin manually, because `plugin_lang_get()`, which is [called in SourceGenericPlugin::register()](https://github.com/mantisbt-plugins/source-integration/blob/master/Source/MantisSourcePlugin.class.php#L163) should in theory already take care of this operation, since the 2nd param is given as 'Source'.

> In the course of lang_get mantis tried to load language files from "[...]/plugins/SourceGeneric" folder

I don't have time to check in detail now; it would be interesting to know what the call stack looks like at this point. Could you provide this information ?

**Comment by flohmueller** [comment]
Oh my - Sorry.. I didn't provide the version we've installed. Looks like my error was fixed long ago, but the company I'm working for never upgraded: https://github.com/mantisbt/mantisbt/commit/9dda347b2b87f91b7432319582d064d38cd99f91 

Sorry for wasting your time.. ;-)
