### ISSUE TITLE
Import Error using PHP

### ISSUE THREAD

**Issue by diemuzi** [mantisbt-plugins/source-integration#118]
I setup GitWeb and tested the Mantis GUI for importing the data which works just fine.

I've also tested that the curl option works:
curl "http://bugs.sitegoodies.net/plugin.php?page=Source/import&id=all&api_key=XXXXXXX"

However when testing the php command line I'm receiving an APPLICATION ERROR #200
php -f plugin.php page=Source/import id=all api_key=XXXXXXX

Of course XXXXXXX is a valid API Key

I'm currently using the latest versions of Mantis and the Plugins. This is a fresh install as of today (03-13-2015)

**Comment by bright-tools** [comment]
I can see this too.  More specifically I get:
    A required parameter to this page (page) was not found.

I've had a quick look at this and I can't see how it's supposed to work when using the command line.  `plugin.php` uses the following call in order to retrieve the page:
    $f_page= gpc_get_string( 'page' )
The implementation of `gpc_get` considers the contents of `$_POST` and `$_GET`, but does not look in `$_SERVER['argv']`, hence the command line parameters are simply ignored.

If this is the case then it seems that there are a few options:
1. Update plugin.php in order to populate `$_GET` from `$argv` when using CLI mode
2. Update `gpc_get()` to consider `$argv` when using CLI mode
3. Deprecate this functionality and remove from the documentation

@dregad would you care to weigh in?

**Comment by dregad** [comment]
I'm not sure the plugin was ever intended to work from CLI.

With regards to the proposed options, I'm not very keen on updating MantisBT core without careful analysis, especially something as central as gpc api.

With regards to deprecating functionality, which documentation are you referring to ?

**Comment by bright-tools** [comment]
It's mentioned in [README.md](https://github.com/mantisbt-plugins/source-integration/blob/master/README.md), under point 10, choice 'b'.  If this is the way you favour then I can update the file appropriately.

**Comment by dregad** [comment]
I just checked, this was added in 3a6d66ca0d0afe55c34fc14fbf24252ee9c341da. I just merged that in, but never actually tested that usage. That being said, the readme refers to php-cgi, not CLI... Maybe @roman-1983 can comment.

**Comment by roman-1983** [comment]
Just make sure to use `php-cgi` as mentioned in the README.md. The php-cgi binary implements the CGI interface, which allows you to pass parameters on the command line:

`php-cgi -f ~//mantis/plugin.php page=Source/import id=all api_key=valid-key-here`

**Comment by dregad** [comment]
Thanks for the feedback @roman-1983.

I would suggest that we amend the Readme to clarify the distinction between php-cgi and php (cli), to avoid future confusion.

**Comment by roman-1983** [comment]
Okay i will send a merge request for that tomorrow.
