### ISSUE TITLE
Gitlab multi language commit message not supported

### ISSUE THREAD

**Issue by heeseunglee** [mantisbt-plugins/source-integration#130]
Thank you for developing such a nice and powerful plugins for gitlab.
It works just great but when i sync from gitlab, the commit message i wrote in Korean, Japanese as well as Chinese does not seems to be printed write in mantis.

changeset looks like below

Issue 0000001
ì¬ë¯¸ìë¤

**Comment by dregad** [comment]
Do you have the right codepage settings (UTF8) in your Mantis DB ?

**Comment by heeseunglee** [comment]
yup!
just for incase i tried to var_dump t_data from core/json_api.php without utf8_encode,
it works fine.
so temporarily i changed the code from $t_json = json_decode( utf8_encode($t_data) ); to $t_json = json_decode( $t_data );

but i know that i won't fix for every cases.

i assume that some kind of problem occurs receiving the json data from gitlab page.

**Comment by dregad** [comment]
Based on the information you just provided, I would assume that Gitlab is returning UTF8-encoded data, so having the MantisBT API encoding it again (https://github.com/mantisbt/mantisbt/blob/master-1.2.x/core/json_api.php#L41) is corrupting it. 

If that is indeed the case, then it's a bug in MantisBT core, and not with the plugin.

Since I don't use Gitalb myself, can you please confirm whether the data retrieved from the Gitlab API is indeed UTF-8 encoded ? (maybe `var_dump( mb_detect_encoding( $t_data ) );`)

**Comment by heeseunglee** [comment]
i thought so too
i will let you know

**Comment by dregad** [comment]
Since you did not provide any feedback, I'm closing this issue now. Feel free to reopen it if necessary.
