### ISSUE TITLE
Git / Gitlab: Add suport for Git-Flow / Gitflow

### ISSUE THREAD

**Issue by hcw70** [mantisbt-plugins/source-integration#148]
We currently use git-flow to work with the git repository and also want a mantis integration.

However, in git-flow as we use it, we dont mention the CR id in the commit comment but in the name of the feature branch, since development of a feature involves many commits.

So every commit which goes to branch i.e. "feature/CR_XXX_Implement:Stuff" (with repository-specific branch prefix, "feature/CR_" in this example) should be associated with mantis ticket XXX.

 Could this be implemented / configured in the Source-Integration plugin?

Kind regards

Hauke

**Comment by dregad** [comment]
The plugin works based on individual changesets (i.e. commits), and switching to using branches for issue association would be a significantly different design which will likely require complex changes. I don't see this happening, unless you're willing to contribute a pull request; if you do so, I would advise to do it in a way that can apply to all git-based plugins if possible.

I would suggest the following alternative methods
- Reference the Issue (i.e. `Fixes #xxx`) just once in the **merge commit** when the feature/hotfix is accepted into its base branch 
- Reference the issue in **each commit**. If you don't want the issue to close automatically, the reference should be `Issue #xxx` instead of `Fixes #xxx`

**Comment by hcw70** [comment]
If i reference the issue in the merge commit, will then all commits in the to-be-merged branch be associated with the mantis ticket?

**Comment by dregad** [comment]
No, only the merge commit
