### ISSUE TITLE
For hosted case, hide Github App ID / Secret from UI

### ISSUE THREAD

**Issue by vboctor** [mantisbt-plugins/source-integration#177]
In MantisHub, the Github Application ID / Secret are expected to be created once by MantisHub, and kept secret and not made visible to the administrators.

I expect the same requirement will apply to other providers like Bitbucket that use OAuth and depend on app being registered with the source control hosting service.

I'm opening this to capture suggestions for the approach.

**Comment by vboctor** [comment]
Here are some options that I can think of:

1. Use config_get_global( 'github_app_id', '' ) and config_get_global( 'github_app_secret' ).  If empty, use default behavior, otherwise, hide app id / password from form.  Do the same for the logic that uses the app id and secret.
2. Add an extra plugin config option that has no UI, if set, then hide the app id/secret.  However, to be secure, this should be global only.  The plugin will have to add it to the global only array.
3. Fork and modify the code.

**Comment by dregad** [comment]
I'm not sure I fully understand the use case here. Does this mean that as a MantisHub customer, I am administrator but I can't maintain my own settings for the source control integration ?

WRT your proposed options:

1. I think it's conceptually wrong to rely on global configuration. IMO plugins should only use their own settings
2. How should this option be set, then ? Modifying the plugin code ? I haven't looked at the logic to update the global array, but I also don't really like this idea.
3. Sounds like the best approach to me...

**Comment by morgant** [comment]
I also think Approach # 3 is best, but don't quite understand why it's necessary.

I believe the current implementation expects a GitHub Application to be created per account/organization in order to allow access to that account's/organization's repositories. Having one account hard-coded for MantisHub would not allow customers to add their own applications to gain access to their repos.

Am I misunderstanding the use case?
