### ISSUE TITLE
SVN: Fix for issue #167 missing on branch modern-ui

### ISSUE THREAD

**Issue by obmsch** [mantisbt-plugins/source-integration#183]
This is kind of strange as the fix has been commited (dregad Aug 3, 2016: f9fe2e9). Browsing the repo at this point in history confirms that. And is still present after the last commit on that day (706d0e0).

Browsing the repo after the next commit (vboctor Aug 28, 2016: 801ff13) shows the fix isn't there any more. **And this commit doesn't change the relevant file**.

**Comment by dregad** [comment]
This is most likely due to an incorrectly merged conflict at 8cb5761585f18fc92340f0b78cf4cb867208fb9c.

**Comment by obmsch** [comment]
So the history of a file is altered without a "visible commit" on that file in the given branch? If that's the case, I really don't get the rationale of it. Why on earth a decent (d)vcs would allow this at all?

As my understanding of git presently is limited at best, I take it to the future to make any sense out of this.

**Comment by dregad** [comment]
The logic behind this is because the "reference" branch in this case is *modern-ui*; the changes occured only in the *master* branch, which was merged into *modern-ui*; at that point, a conflict was identified, which was resolved as ignoring the changes from the "remote" branch (*master*) so technically the file was not changed in the base branch *modern-ui*. This is the reason why merge commits generally list the files for which a conflict occurred, as it allows to identify this kind of issues.

If you're not using one already, I suggest you pick a graphical tool to view the git history log, it really helps to understand.
