### ISSUE TITLE
Syntax error in MantisSourceGitBasePlugin.class.php v2.0.0

### ISSUE THREAD

**Issue by vboctor** [mantisbt-plugins/source-integration#199]
Error from Apache errors.log:
```
[Mon Mar 06 03:53:22.474467 2017] [:error] [pid 6908] [client 50.135.100.5:60327] PHP Parse error:  syntax error, unexpected '.', expecting ',' or ';' in .../plugins/Source/MantisSourceGitBasePlugin.class.php on line 25, referer: ...?
```

Issue fixed by changing:

	private $valid_branch_regex = '%'
		# Must not start with '/'; cannot contain '/.', '//', '@{' or '\';
		# cannot be a single '@'.
		. '^(?!/|.*([/.]\.|//|@\{|\\\\)|@$)'
		# One or more chars, except the following: ASCII control, space,
		# tilde, caret, colon, question mark, asterisk, open bracket.
		. '[^\000-\037\177 ~^:?*[]+'
		# Must not end with '.lock', '/' or '.'
		. '(?<!\.lock|[/.])$'
		. '%';

to:

	private $valid_branch_regex = '%^(?!/|.*([/.]\.|//|@\{|\\\\)|@$)[^\000-\037\177 ~^:?*[]+(?<!\.lock|[/.])$%';

No change in regular expression, just removed comments and remove concatenations and made it a single string.

**Comment by dregad** [comment]
From https://gitter.im/mantisbt-plugins/source-integration?at=58bd174b1465c46a56f06d2c:
> What version of php did you get the error with

I believe 5.5.9

----

I'm pretty sure I ran this on 5.5.x at some point, since I fixed a bug earlier on what appears to be similar behavior (9d63c3b74669b52e432693487702811100de18a7); this is probably the same root cause.
