### ISSUE TITLE
ERROR 0 thrown when viewing non-existent changeset

### ISSUE THREAD

**Issue by luzpaz** [mantisbt-plugins/source-integration#203]
```
APPLICATION ERROR #0

An error occurred during this action. You may wish to report this error to your local administrator.
Please use the "Back" button in your web browser to return to the previous page. There you can correct whatever problems were identified in this error or select another action. You can also click an option from the menu bar to go directly to a new section.
```

* To reproduce go to: https://freecadweb.org/tracker/plugin.php?page=Source/search&repo_id[]=2&message=py3&offset=2
* Scroll or search down to git commit `e13d4a78`
* Click the _Details_ button (https://freecadweb.org/tracker/plugin.php?page=Source/view&id=6744)
Result: above error

**Comment by dregad** [comment]
The error is triggered because the view page can't find the changeset in the database. It can be reproduced by manually setting the *id* parameter to a value that does not exist in the changeset table's id column (e.g. https://example.com/plugin.php?page=Source/view&id=0)
 
A more specific error message should be displayed, instead of the generic error 0.

Call stack
```
./plugins/source-integration/Source/Source.API.php	1106	-	-	trigger_error	( <string>'0', <integer>256 )
./plugins/source-integration/Source/pages/view.php	14	SourceChangeset	::	load	( <integer>226445 )
./plugin.php	69	-	-	include	( <string>'/home/ubuntu/workspace/plugins/source-integration/Source/pages/view.php' )
```

As to why the search page is listing a changeset that does not exist (or does it ?), I'm not sure. It could be a data error in your MantisBT instance or another bug, but I can't be sure without additional information from your side.

- What is the SQL query being executed by the search page in the link you provided above ?
- Does the changeset with id 6744 exist in the *Source_changeset* table ?
- Are there matching records (with change_id = 6744) in *Source_bug* or *Source_file* tables ?

**Comment by luzpaz** [comment]
CC @kkremitzki

**Comment by dregad** [comment]
Without feedback from you on the 3 questions above, or other evidence that this is a bug in the plugin and not a data issue on your side, I'll recategorize this as an enhancement to display a more helpful error message.

**Comment by luzpaz** [comment]
We're looking further in to this....will report back when we have results. Thanks!

**Comment by dregad** [comment]
Without feedback from you, I'm re-categorizing this as mentioned in my previous message.

**Comment by luzpaz** [comment]
@dregad sorry for not responding. Will take a look at the fix once the new release is out
