### ISSUE TITLE
Cannot install with MariaDB, MantisBT Core version 2.3.0

### ISSUE THREAD

**Issue by lavacano201014** [mantisbt-plugins/source-integration#212]
Difficult to explain adequately, so I'll just show you what it's doing.

![screenshot_20170408_093923](https://cloud.githubusercontent.com/assets/4407155/24830666/46112bd4-1c3f-11e7-8fb2-b9d1773158ce.png)

```
MariaDB [mantis]> show tables;
+------------------------------------+
| Tables_in_mantis                   |
+------------------------------------+
| mantis_Sou_mantis                  |
| mantis_Sour_mantis                 |
| mantis_Source_ch_mantis            |
| mantis_Source_mantis               |
| mantis_Source_rep_mantis           |
( default tables truncated )
+------------------------------------+
```

Uncertain if this is a bug in the plugin or in MantisBT itself. MariaDB user has been granted all privileges on mantis database and still no joy. Vanilla Mantis works fine.

**Comment by lavacano201014** [comment]
Well the problem definitely isn't MariaDB, because I migrated the whole thing over to PostgreSQL 9.5 and I'm having the same problems. (Fortunately, this is still a relatively new Mantis instance, so there wasn't much data to handle)

At this point, I'm just stuck at "it doesn't work".

**Comment by dregad** [comment]
I am not able to reproduce the problem.

Does this also happen with a fresh install ?
Can you specify: OS, PHP, MantisBT, Source Integration versions ?
Can you provide error output with `$g_show_detailed_errors = 1;` (remove any sensitive information if needed)

**Comment by lavacano201014** [comment]
Ubuntu 16.04, PHP 7.0.15, MantisBT 2.3.0 and Source Integration is on the latest commit from this repository (0ff093492b923e0dfa4311d8b217e5b1fc3efbf1).

[Installation attempt log.](https://github.com/mantisbt-plugins/source-integration/files/913946/install.txt) I should note that for some reason Mantis is now complaining about block 0 instead of block 12.

**Comment by dregad** [comment]
I have pretty much the same setup here (except MySQL instead of MariaDB), but we have already ruled out the RDBMS as the cause here.

Thanks for the log (HTML format would have been easier to read...). At first glance, it appears that the schema definition somehow does not generate the table names properly, maybe a problem with *plugin_table()* function ? 

Again, this works fine on the 3 distinct setups I have tried, and since you did not answer

> Does this also happen with a fresh install ?

I'm wondering if this could be due to something specific to your configuration. Did you customize anything ? What are your config_inc.php settings ?

**Comment by dregad** [comment]
I had a closer look, and there is definitely something fishy with the way your table names are built. 

Plugin table | Actual physical table name° | Your results
---|---|---
branch      | mantis_Source_branch_table      | mantis_Source_mantis          
bug         | mantis_Source_bug_table         | mantis_Sou_mantis             
changeset   | mantis_Source_changeset_table   | mantis_Source_ch_mantis       
file        | mantis_Source_file_table        | mantis_Sour_mantis            
repository  | mantis_Source_repository_table  | mantis_Source_rep_mantis      
user        | mantis_Source_user_table        | mantis_Sour_mantis            

° with MantisBT default settings

It's worth noting that if we exclude the `mantis` prefix and suffix from your table names, the remaining "middle" part looks like a substring of the actual name, of a length matches that of the plugin's base table name, i.e. `bug` -> `Sou`, `changeset` -> `Source_ch` etc.

So, this definitely is not a problem caused by the source integration plugin.

**Comment by dregad** [comment]
I think just I realized what is wrong with your setup: you must have set `$db_table_plugin_prefix = 'mantis';` (why !?).

This would cause database API's db_get_table() function to process the plugin table as if it were a legacy table name (i.e. Mantis 1.2 style, with a `mantis_` prefix).

As a side note, Mantis will trigger a deprecated warning in this case, but depending on your error reporting settings you may not have seen it.

I have opened an [issue in MantisBT tracker](http://www.mantisbt.org/bugs/view.php?id=22715) to improve the legacy table name detection mechanism to avoid this problem. Until then, I suggest you change your prefix/suffix configuration and adjust your database schema by renaming tables accordingly. You can drop the invalid Source integration tables and reinstall the plugin.

**Comment by lavacano201014** [comment]
>I think just I realized what is wrong with your setup: you must have set $db_table_plugin_prefix = 'mantis'; (why !?).

I have absolutely no idea, but that was the line in `config_inc.php`. I altered it to `$g_db_table_prefix = "mantis2_"` (and renamed tables accordingly via Python script) and everything works again. The only thing I consciously remember altering in the original configuration process is my DB information (and adding an extra status) so this must be some sample config I grabbed from Google because I wasn't aware of the presence of a sample file in the tarball.
