### ISSUE TITLE
Closed issue not consistently struck-out on SI commit details

### ISSUE THREAD

**Issue by luzpaz** [mantisbt-plugins/source-integration#234]
![image](https://user-images.githubusercontent.com/4140247/28878279-cab5a35a-776c-11e7-9c88-d2096925fe8b.png)
Notice how the ticket references to Issue 3111 differ. One is struck out and the other isn't. Why is that the case? In other words, they should both be struck out because that ticket is resolved. 
Latest MantisBT and SI plugin

**Comment by dregad** [comment]
This is due to the _Affected Issues_ list calling `bug_format_id()` (which just pads the id with zeros), whereas the Changeset message is handled by MantisCoreFormatting plugin; that ultimately relies on `string_get_bug_view_link()` which decorates the anchor with the `resolved` CSS class.

Replacing the function call would be an easy fix, but as a consequence the _Affected Issues_ bug links would gain a tooltip with the issue's description, which is redundant since it is already displayed right next to the issue id.

I think a better approach would be to display a status color box next to the issue id (similar to the display in view_all_bug_page.php and my_view_page.php).

**Comment by dregad** [comment]
Something like this, including tooltip with status description when hovering over the colored box:
![screenshot-20170914-1806](https://user-images.githubusercontent.com/449891/30440663-85cdf378-9977-11e7-8916-46b5eb95120d.png)
