### ISSUE TITLE
Question: Link to existing repository on another server?

### ISSUE THREAD

**Issue by pedwik** [mantisbt-plugins/source-integration#239]
We use using subversion (Collabnet Edge and with ViewVC) hosted on a Windows/IIS server, and MantisBT (ver 2.5) hosted on an Apache server, and want to hook up MantisBT to svn. Purpose: When a developer commits a change to svn, MantisBT should be notified and the ticket updated.  We have installed the source integration plugins (Source, SourceSVN, and SourceViewVC). When configuring the Source plugin, there is a function "Create repository", but I do no not want to create a new repo but link to an existing. Grateful for any tips, have googled around without success.

**Comment by dregad** [comment]
The *Create Repository* function in the SI plugin does not actually create a VCS repo, its purpose is to record the necessary information and parameters for your existing repository. Hope this clarifies.

**Comment by pedwik** [comment]
That sounds promising, thank you. My concern was that one documentation said the data import could be very time consuming.

**Comment by bright-tools** [comment]
When you create the repository in Mantis it will go & query the actual repository for the changeset history.  Depending on the number of commits to the repo, this can take a while.

**Comment by pedwik** [comment]
Since our subversion is on another server (Windows 2016) I am unclear how to set the following parameters and would be grateful for any guidance:
SVN: Path to binary
SVN: Command arguments
SVN: Use Windows `start`

**Comment by dregad** [comment]
I'm afraid I can't help you much here - I haven't used SVN at all for many years... I would guess that you need to have the client installed on the MantisBT server.

> should subversion push commit info to Mantis, or should Mantis pull it from subversion (by adding a cron job)

IIRC, you can do both, i.e. setup a cron with the import script, or setup a [post-commit hook](https://github.com/mantisbt-plugins/source-integration/blob/master/SourceSVN/post-commit.tmpl)

**Comment by pedwik** [comment]
Can a url be entered for "SVN: Path to binary"? Our web host for the MantisBT system does not allow installation of svn client libraries on shared hosting.

**Comment by dregad** [comment]
I don't think so. You can try...

**Comment by morgant** [comment]
@pedwik It's been a while since I used SVN as well and haven't used it with SouceIntegration & SourceSVN. It doesn't hurt to try using a URL for the path to the SVN binary, but I agree that it's unlikely to work.

You mentioned installing the SVN client libraries on shared hosting. Can you install the `svn` client binaries (or do they already have them installed)? If so, you should be able to check out your remote SVN repo locally on your MantisBT host, automate running `svn update` or whatever else is necessary to keep it up-to-date, and then point your SourceSVN configuration at that local repo. If not, I'd suggest try switching to some kind of virtual/dedicated hosting instead of shared for your MantisBT server.

**Comment by dregad** [comment]
@pedwik should I infer from #241 that this issue can be closed ?

**Comment by pedwik** [comment]
Yes

**Comment by dregad** [comment]
Thanks for your feedback.
