### ISSUE TITLE
SVN integration through a firewall

### ISSUE THREAD

**Issue by ShaunAtSNA** [mantisbt-plugins/source-integration#263]
We are using MantisHub for our issue tracking and I'm wondering whether it's possible to integrate with SVN repositories through a firewall ?

I understand that this is not strictly related to the MantisBT project and the MantisHub folks have told me that the source control plugin will not work with repositories that are not publicly accessible on the cloud.

However, they suggested that I ask here whether this is actually possible and indicated that they might be able to provide this kind of support depending on the feedback I receive.

Thanks in advance for any advice...

**Comment by dregad** [comment]
If my understanding is correct, you want MantisHub to access an SVN repo that sits in your company's internal network ?

In that case, I think you should work with your network/security engineers to open up the firewall as appropriate, so that the relevant IP addresses / ports for your SVN infrastructure can be accessed by the MantisHub servers. This has nothing to do with the Source Integration Plugin or MantisBT.

As an alternative, you could self-host MantisBT internally instead of using MantisHub.

I don't think there is much more that I can do to help here... As for the MantisHub folks, except telling you which IP addresses your firewall folks will need to authorize, I'm not sure how they could assist you.

**Comment by ShaunAtSNA** [comment]
Your understanding is absolutely correct.

Thank-you very much for the answers and advice - I had kind of anticipated what you might say.
I guess my next step is to talk to our network/IT guys as you suggest...

**Comment by dregad** [comment]
Thanks for the feedback.
