### ISSUE TITLE
Switch to GitLab API V4

### ISSUE THREAD

**Issue by uxmaster** [mantisbt-plugins/source-integration#270]
`{"error":"API V3 is no longer supported. Use API V4 instead."}`

**Comment by dregad** [comment]
Thanks for the report. The GitLab plugin is community-maintained. Pull requests to adapt it to the latest GitLab API are welcome.

**Comment by dregad** [comment]
I had a quick look and we only use 3 API calls : `git grep -i 'this->api_uri'`

- SourceGitlab.php:162:           $t_uri = $this->api_uri( $p_repo, "projects/$t_hub_reponame_enc" );
- SourceGitlab.php:256:       $t_uri = $this->api_uri( $p_repo, "projects/$t_repoid/repository/branches" );
- SourceGitlab.php:317:           $t_uri = $this->api_uri( $p_repo, "projects/$t_repoid/repository/commits/$t_commit_id" >

As far as I can tell, these should not be affected by changes in API v4, so it should be enough just to modify the endpoint.

@uxmaster since I don't use GitLab, would you be able to test if everything works correctly after updating SourceGitlab.php line 186, replacing `api/v3/` by `api/v4/` ?

**Comment by uxmaster** [comment]
Yes. It seems to work correctly after updating the line. Thanks.

**Comment by dregad** [comment]
OK, I'll commit the change then. Thanks for the feedback.
