### ISSUE TITLE
missing pagination in SourceGitLab

### ISSUE THREAD

**Issue by fredericve** [mantisbt-plugins/source-integration#271]
When a project in gitlab contains more than 20 branches the source integration might fail since the gitlab API by default only returns 20 items.

As a workaround on our instance I just added `per_page=100` to the request uri, which results in working source integration. But as I said, that's a workaround, not a solution. Ideally pagination should be implemented.

**Comment by dregad** [comment]
Gitlab API handles pagination through metadata in the request's headers.
 
The *json_url()* MantisBT core api used by the plugin to retrieve data from Gitlab webservice is very basic, and only returns the payload but not the headers, so this would require a different implementation, e.g. using GuzzleHttp library (bundled with MantisBT since 2.5.0).
