### ISSUE TITLE
GitHub Import Failure

### ISSUE THREAD

**Issue by spmeesseman** [mantisbt-plugins/source-integration#319]
The first repository I tried importing worked, but the second repository failed with the error:

![github-import-error](https://user-images.githubusercontent.com/48744816/62419056-d55ab100-b645-11e9-800e-bee8da124430.png)

Looks to have imported some or all of it though:
![github-import-error-2](https://user-images.githubusercontent.com/48744816/62419092-9547fe00-b646-11e9-96f2-b1a9a59df5ed.png)

**Comment by dregad** [comment]
I tried googling `f09f9a80`, and it would appear to be a ["rocket" 🚀 emoji](https://www.fileformat.info/info/unicode/char/1f680/index.htm). Can you identify the offending commit in your repo ? If it's public, maybe post a link to it.

Unicode support in MySQL is only fully operational with `utf8mb4` charset; otherwise, the DB can only handle 3 bytes chars with the `utf8` default. Please check your DB for *mantis_plugin_Source_changeset_table* and confirm charset for *message* column.

This is possibly hitting a [known issue with MantisBT](https://mantisbt.org/bugs/view.php?id=20431); we currently have a workaround in place, with db_mysql_fix_utf8() function that replaces the offending char with `�`.

**Comment by spmeesseman** [comment]
aaahhh, i would never even have thought to google that hex code.  i see, yup that is the semantic-release emoji and I used it in my app-publisher app badge too.  I will check to see how it handled that when i get a free moment and will post back

**Comment by dregad** [comment]
Since you have not provided any feedback, I assume that you found a solution or workaround to your issue.
