### ISSUE TITLE
Bitbucket: "Resource not found" retrieving Changesets from branch containing "/"

### ISSUE THREAD

**Issue by Hainv201** [mantisbt-plugins/source-integration#376]
The plugins is not able to retrieve changesets from branches contains "/" on their branch name from Bitbucket.
Examples:
Retrieving feature/ChangeRequests ... failed (Resource not found).
Retrieving feature/DescriptiveNames ... failed (Resource not found).
Retrieving feature/initial_commit ... failed (Resource not found).

Problem:

if( !preg_match( '/\*|^[a-zA-Z0-9_\., -]*$/', $f_master_branch ) ) {
			echo 'Invalid parameter: \'Primary Branch\'';
			trigger_error( ERROR_GENERIC, ERROR );
		}
From SourceBitBucket.php is not allow to have "/" in the branch name

**Comment by dregad** [comment]
Can you please check if replacing the above-mentioned code block by
```php
$this->ensure_branch_valid( $f_master_branch );
```
fixes the problem ?

**Comment by Hainv201** [comment]
@dregad Thanks for your answer. It helps to use branch with "/" as the Primary Branch. But I tried to retrieve changesets, it did not work. I got the same messages. I think the problem is this function:
`public function import_commits( $p_repo, $p_commit_ids, $p_branch = '' ) {
		static $s_parents = array();
		static $s_counter = 0;

		$t_username = $p_repo->info['bit_username'];
		$t_reponame = $p_repo->info['bit_reponame'];

		if( is_array( $p_commit_ids ) ) {
			$s_parents = array_merge( $s_parents, $p_commit_ids );
		} else {
			$s_parents[] = $p_commit_ids;
		}

		$t_changesets = array();

		while( count( $s_parents ) > 0 && $s_counter < 200 ) {
			$t_commit_id = array_shift( $s_parents );

			echo "Retrieving $t_commit_id ... ";
			$t_json = null;
			if( empty($this->commits_cache[$t_commit_id]) ) {
				$t_url  = $this->api_url( "repositories/$t_username/$t_reponame/commit/$t_commit_id" );
				$t_json = $this->api_json_url( $p_repo, $t_url );
			} else {
				$t_json = $this->commits_cache[$t_commit_id];
			}

			if( false === $t_json || is_null( $t_json ) ) {
				# Some error occured retrieving the commit
				echo "failed.\n";
				continue;
			} else if( !property_exists( $t_json, 'hash' ) ) {
				echo 'failed (', $t_json->error->message, ").\n";
				continue;
			}

			list($t_changeset, $t_commit_parents) = $this->json_commit_changeset( $p_repo, $t_json, $p_branch );
			if( $t_changeset ) {
				$t_changesets[] = $t_changeset;
			}

			$s_parents = array_merge( $s_parents, $t_commit_parents );
		}

		$s_counter = 0;
		return $t_changesets;
	}`.

**Comment by dregad** [comment]
I had a look at this today, apologies for the long delay.

So there are 2 issues:

### Validation of branch selection

Can be fixed as mentioned in my earlier note (https://github.com/mantisbt-plugins/source-integration/issues/376#issuecomment-886114442).  Note that it would actually be more appropriate to use
```php
$this->validate_branch_list( $f_master_branch );
```

### Resource not found error 

I confirm the issue, which occurs when importing changesets for a branch having `/` in its name.

The plugin makes the following Bitbucket API call :
`repositories/$t_username/$t_reponame/commit/$t_commit_id`, where in the loop's first iteration _$t_commit_id_ is the branch name, e.g. https://bitbucket.org/api/2.0/repositories/dregad/test/commit/release/v2

```json
{
  "type": "error",
  "error": {
    "message": "Resource not found",
    "detail": "There is no API hosted at this URL.\n\nFor information about our API's, please refer to the documentation at: https://developer.atlassian.com/bitbucket/api/2/reference/"
  }
}
```

So AFAICT, this is actually caused by the Bitbucket API itself. I found this: https://jira.atlassian.com/browse/BCLOUD-9969

As a workaround, we could lookup the branch's target commit if the name contains a `/`.

**Comment by 5dive** [comment]
See if this PR helps you:

https://github.com/jenkins-x/go-scm/pull/295/

**Comment by dregad** [comment]
@5dive thanks for the link
I think I got this already - pretty much the same approach, i.e. if the branch contains a `/`, get the commit SHA via `repositories/$t_username/$t_reponame/refs/branches/$t_branch` (target->hash)
