### ISSUE TITLE
GitLab

### ISSUE THREAD

**Issue by TimLiGood** [mantisbt-plugins/source-integration#412]
This issue previously worked fine
But upgrading GitLab to v16.8 started getting errors
Don't know how to solve it?

Site Information
![image](https://github.com/mantisbt-plugins/source-integration/assets/132968931/957e5fbc-3695-4557-8657-45646f4bb666)
![image](https://github.com/mantisbt-plugins/source-integration/assets/132968931/301c6710-625d-4a70-9daa-bac418ba6914)
![image](https://github.com/mantisbt-plugins/source-integration/assets/132968931/571b14eb-aa16-4275-a99f-a81a9150f842)

setting
![image](https://github.com/mantisbt-plugins/source-integration/assets/132968931/dd2ac729-360a-4cf8-8e0e-e961d41ada72)
Import Everything
![image](https://github.com/mantisbt-plugins/source-integration/assets/132968931/3df42116-2744-4222-8efa-11fad9051c6b)
but real have data
![image](https://github.com/mantisbt-plugins/source-integration/assets/132968931/d0d46ba2-b937-46dc-8f89-c63bb43024be)

**Comment by dregad** [comment]
This error occurs when the plugin is unable to retrieve data from the GitLab URL.

https://github.com/mantisbt-plugins/source-integration/blob/88bdd22e103b70d92531e8ed52f3ecfce5dc1146/SourceGitlab/SourceGitlab.php#L320-L323

Since the URL appears to be correct based on your last screenshot, it probably means that your web server is for some unknown reason not able to connect to it, or that the returned data is not valid JSON.

For troubleshooting, you can try to add `var_dump($t_data, $t_json);` in _json_url()_ function [after line 44 in MantisBT /core/json_api.php](https://github.com/mantisbt/mantisbt/blob/b8778103a11ddd979a773259323398b3942e24c0/core/json_api.php#L45
).

**Comment by dregad** [comment]
> Did I make a mistake in my modification?

No, your change is correct. 

I didn't expect *url_get()* to return null (it should return false when there is an error). As far as I can tell the only way this could happen, is if the shell_exec() call to run curl fails.

Questions:
- Is the [PHP Curl extension](https://www.php.net/book.curl) installed in your web server ?
- If not, is the server allowed to execute system calls (via [shell_exec](https://www.php.net/function.shell-exec)), and is the curl command available ?
- Are you behind a corporate proxy that could be blocking web access ?

**Comment by TimLiGood** [comment]
Yes,enabled
![image](https://github.com/mantisbt-plugins/source-integration/assets/132968931/69d2f2e2-8690-495e-8764-086f4fedf289)
Are you behind a corporate proxy that could be blocking web access ?   No

**Comment by dregad** [comment]
Would you be able to trace execution of url_get(), and find out which part of the code is returning null and why ?
You can do this with a simple test script like this (save it in your MantisBT root)
```
<?php
include 'core.php';
require_api('url_api.php');
var_dump(url_get( 'https://geneve.ch'));
```
Since you apparently have the curl extension it should not be the case, but if it is indeed the shell_exec() call, then you need to figure out a) why the URL is not retrieved by curl extension and b) why shell_exec() is not executing curl (maybe command is not installed on your system, which would not be too suprising since you're on Windows).

**Comment by dregad** [comment]
I'm sorry, but your last post does not help explaining the problem at all.

The 404 errors are not related to MantisBT or the source plugin in any way. They come from outputting the contents of https://geneve.ch, which was actually just meant as an example URL. You should try again after replacing that with your Gitlab URL. 

I guess this at least proves that you're able to retrieve a website's contents. But since you apparently do not have xdebug extension active, the returned HTML is interpreted as the page's contents, causing the errors you're seeing. If you can't enable xdebug, then you should view the page source to get the actual output.

I expected you to *find out which part of the code is returning null and why ?*, which implies that you need to trace PHP code execution through url_get() function. in other words, you need to tell me which of the *return* statements is producing the `null` result (i.e. after ` @file_get_contents( $p_url );` (line 42), `curl_exec( $t_curl );` (line 72) or `shell_exec( 'curl ' . $t_url );` (line 78).

**Comment by dregad** [comment]
You did not provide any feedback and I'm not able to reproduce, so I'm closing this for now. Feel free to reopen if you can provide a reproducible test case.
